# Generated by Django 5.0.4 on 2024-04-08 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrgBeneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caducidad', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('asignacion', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_aprox', models.CharField(max_length=100)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.alimento')),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgDonante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('area_servicio', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('sitio_web', models.URLField()),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donante')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoP', models.CharField(max_length=100)),
                ('apellidoM', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('etiqueta', models.CharField(max_length=100)),
                ('bibliografia', models.TextField()),
                ('sitio_web', models.URLField()),
                ('foto', models.ImageField(null=True, upload_to='perfiles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDonante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cataloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.IntegerField()),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donante')),
            ],
        ),
        migrations.CreateModel(
            name='Requiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.alimento')),
                ('org_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.orgbeneficiaria')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.IntegerField()),
                ('org_benefica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.orgbeneficiaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.orgbeneficiaria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=100)),
                ('tarea', models.CharField(max_length=100)),
                ('responzable', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proporciona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('org_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.orgbeneficiaria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.producto')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.alimento')),
                ('org_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.orgbeneficiaria')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.voluntario')),
            ],
        ),
    ]
