# Generated by Django 5.0.4 on 2024-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanatural',
            name='status',
            field=models.IntegerField(blank=True, choices=[('V', 'Voluntario'), ('D', 'Donante'), ('R', 'Receptor')], null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='status',
            field=models.IntegerField(blank=True, choices=[('V', 'Voluntario'), ('D', 'Donante'), ('R', 'Receptor')], null=True),
        ),
    ]
