# Generated by Django 5.0.4 on 2024-04-10 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_alter_producto_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cataloga',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donacion',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proporciona',
            name='asignacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cataloga',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
